#!/bin/bash

echo "🧪 Testing Suggested Actions Feature"
echo "===================================="
echo ""

echo "✅ Implementation Complete!"
echo ""
echo "What was added:"
echo "  1. Action Suggester Service (backend/app/core/action_suggester.py)"
echo "  2. Updated Chat API to include suggested actions"
echo "  3. Action bubbles UI in chat interface"
echo ""
echo "Supported Services:"
echo "  🏠 Land Services:"
echo "     - Land Registration"
echo "     - Title Transfer"
echo "     - Land Subdivision"
echo ""
echo "  ✈️ Immigration Services:"
echo "     - Visa Application"
echo "     - Passport Application"
echo "     - Resident ID"
echo "     - Laissez-Passer"
echo ""
echo "How to test:"
echo "  1. Restart backend: pkill -f uvicorn && cd backend && source venv/bin/activate && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &"
echo "  2. Go to http://localhost:3001/chat"
echo "  3. Try these questions:"
echo ""
echo "     Land Services:"
echo "       - 'What is the price for land registration?'"
echo "       - 'How do I transfer my land title?'"
echo "       - 'Tell me about land subdivision'"
echo ""
echo "     Immigration Services:"
echo "       - 'How do I apply for a visa?'"
echo "       - 'What is the cost of a Rwandan passport?'"
echo "       - 'Tell me about Resident ID'"
echo ""
echo "  4. Look for action bubbles below the AI response!"
echo ""
echo "Action Types:"
echo "  🔵 Primary (Blue) - Main action (e.g., 'Register Land Now')"
echo "  ⚪ Secondary (Gray) - Supporting actions (e.g., 'View Requirements')"
echo ""
